version: "3.9"
services:
  cyberowl_db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 3306:3306
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: local_db
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cyberowl_adminer:
    container_name: cyberowl_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
